# Generated by Django 3.1.4 on 2020-12-28 18:33

import blog.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Blog Başlığı')),
                ('category', models.CharField(max_length=255, verbose_name='Kategori Adı')),
                ('content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi')),
                ('edited_on', blog.models.AutoDateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Düzenlenme Tarihi')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Blog Resmi')),
                ('slug', models.SlugField(editable=False, max_length=150, null=True, unique=True, verbose_name='Adres')),
                ('status', models.CharField(choices=[('draft', 'Beklemede'), ('published', 'Yayında')], default='published', max_length=10, verbose_name='Durum')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('content', models.TextField(verbose_name='Yorum')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Yorum Tarihi')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10, verbose_name='Durum')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
        ),
    ]
